### ISSUE TITLE
Apakah bisa mengubah versi tafsir?

### ISSUE THREAD

**Issue by alfanzain** [gadingnst/quran-api#21]

**Comment by sutanlab** [comment]
untuk sekarang belum bisa mas, karna data tafsir yang incredible yg tersebar di internet sekarang sumbernya cuma dari KEMENAG. @alfanzain

**Comment by sutanlab** [comment]
untuk sekarang belum bisa ya mas, karna data tafsir yg kredibel tersebar di internet sekarang sumbernya cuma dari KEMENAG, jadi saya cuma pake itu. @alfanzain

**Comment by oottoohh** [comment]
tafsir nya tafsir dari ulama siapa yaa?

**Comment by alfanzain** [comment]
> tafsir nya tafsir dari ulama siapa yaa?

dari KEMENAG

**Comment by oottoohh** [comment]
saya nanya author nyaa bang maksudnya @alfanzain

**Comment by alfanzain** [comment]
> saya nanya author nyaa bang maksudnya @alfanzain

iya, setauku tafsir ini authornya KEMENAG
yg berarti authornya oleh 1 kelompok, bukan perorangan

**Comment by oottoohh** [comment]
@alfanzain di readme halaman depan nya bilang itu dia pake dari shahih international, nah yang jadi pertanyaan shahih international itu based on website atau apa.

**Comment by alfanzain** [comment]
> @alfanzain di readme halaman depan nya bilang itu dia pake dari shahih international, nah yang jadi pertanyaan shahih international itu based on website atau apa.

mungkin yg anda maksud ini ya

> [Al-Quran-ID-API](https://github.com/bachors/Al-Quran-ID-API) = Indonesia tafsir surah [note: ambiguous revelation type on surah 13 and 55 in this source. So, I changed it to medinan (according to sahih international data)]

AFAIK yg dimaksud adalah kasus tipe turunnya surah ada di mana yg ambigu, bukan tafsirnya
dari sumbernya (https://github.com/bachors/Al-Quran-ID-API?tab=readme-ov-file) tidak dijelaskan sumbernya dari mana

konteks dari issue ini lebih ke tafsir suratnya
mungkin bisa buat issue baru untuk bahasan dengan konteks yg berbeda
